#!/usr/bin/env python

import smtplib
import sys
import time
import urllib2

FROM_ADDR = 'mmonitor@corp.mixpanel.com'
TO_ADDR = 'integration-test@mixpanel2.pagerduty.com'

class HeadRequest(urllib2.Request):
    def get_method(self):
        return 'GET'

def check_if_sites_down():
    # simply pings www.mixpanel.com and api.mixpanel.com
    # if not 200, kicks off pagerduty incident via email

    check_site('http://mixpanel.com')
    check_site('http://api.mixpanel.com')

def check_site(url):
    print "testing site:", url # convert to logging
    try:
        resp = urllib2.urlopen(HeadRequest(url), data=None, timeout=30) # seconds
        if resp.getcode() != 200:
            send_pagerduty_email(url, resp.msg)
        else:
            print "site ok:", url
    except Exception as ex:
        print "exception!", str(ex)
        pass # todo: logging. should also possibly send pagerduty if monitoring fails

def send_pagerduty_email(url, body):
    try:
       msg = format_pagerduty_email(FROM_ADDR, TO_ADDR, url, body)

       smtp = smtplib.SMTP('localhost', 25, timeout=30)
       smtp.ehlo_or_helo_if_needed()
       smtp.sendmail(FROM_ADDR, TO_ADDR, msg)
       smtp.close() # todo: move to finally block
    except:
        pass

def format_pagerduty_email(from_addr, to_addr, url, body):
    gmt = time.gmtime()

    # divide into 15 minute chunks so that PagerDuty can de-dup
    adjusted_minutes = (gmt.tm_min / 15) * 15 # discard remainder
    time_str = time.strftime('%Y_%m_%d %H:'+str(adjusted_minutes).zfill(2), gmt)

    subject = 'site [%s] is possibly down around [%s UTC]' % (url, time_str)
    msg = 'From: %s\nTo: %s\nSubject: %s\n%s\n' % (from_addr, to_addr, subject, body,)
    return msg

if __name__ == '__main__':
    nargs = len(sys.argv)
    if nargs > 1 and sys.argv[1] == 'test':
        # quick test in lieu of proper unit tests
        send_pagerduty_email('http://www.foo.com', 'test msg')
    else:
        # normal usage
        check_if_sites_down()
