#!/usr/bin/env python

import eventlet
eventlet.monkey_patch()

import simplejson as json
from sys import argv
import logging
import subprocess

import settings
from mail import Email
from discovery import discovery
from tests import tests

logging.basicConfig(filename='mmonitor.log', format='%(asctime)s %(levelname)-7s %(message)s', level=logging.INFO)

status_file = 'status.json'

logging.info('starting')
try:
    fp = open(status_file, 'r')
    status = json.load(fp)
    fp.close()
except IOError:
    status = {'servers': {}}

email = Email()
test = []
for t in settings.tests:
    test.append(t(email))

if len(argv) > 1 and argv[1] == '-a':
    discovery(status, test)
tests(status, test)

status = json.dump(status, open(status_file, 'w'), indent=4, sort_keys=True)
email.flush()

# pagerduty integration, keep simple for now
try:
    subprocess.call(['./mmonitor_pagerduty'])
except:
    logging.exception('could not launch pagerduty test')
