#!/usr/bin/env python

import simplejson as json

import settings
from mail import Email
from tests.mongo import Mongo
from discovery import discovery
from tests import tests

status_file = 'status.json'

try:
    fp = open(status_file, 'r')
    status = json.load(fp)
    fp.close()
except IOError:
    status = {'servers': {}}

email = Email()
test = []
for t in settings.tests:
    test.append(t(email))

discovery(status, test)
tests(status, test)

status = json.dump(status, open(status_file, 'w'), indent=4, sort_keys=True)
email.flush()
